### ISSUE TITLE
Providing token scopes - string or list of strings?

### ISSUE THREAD

**Issue by wchatx** [cognitedata/cdp-spark-datasource#505]
Just want to confirm that token scopes should be provided as a string and not a list of strings. The Cognite Python SDK [expects a list](https://cognite-docs.readthedocs-hosted.com/projects/cognite-sdk-python/en/latest/cognite.html#cogniteclient) so wanted to make sure this was correct.

Thanks!

**Comment by exyi** [comment]
Yes, scopes should be a single string. The individual scopes should be separated by a space, it is then converted to a list: https://github.com/cognitedata/cdp-spark-datasource/blob/master/src/main/scala/cognite/spark/v1/DefaultSource.scala#L266

I think this is because Spark only reliably supports string options.
